field_ownership:
  title: rally
  description: rally
  quarter: rally
  feature: rally
  dependencies: rally
  assignee: gitlab
  state: gitlab
  estimate: gitlab

state_mapping:
  rally_to_gitlab:
    Defined: opened
    In-Progress: opened
    Completed: closed
    Accepted: closed
  gitlab_to_rally:
    opened: In-Progress
    closed: Accepted

labels:
  rally_story: "source::rally"
  rally_task: "source::rally-task"
  managed: "bridge::managed"
